// const corpus: string[] = [
//   'IEM-CNRS, 1919, route de Mende, 34293 Montpellier cedex 5, France',
//   'Institut Européen des Membranes, Centre National de la Recherche Scientifique, 1919, Route de Mende, 34293 Montpellier Cedex 5, France',
//   'Institut Européen des Membranes, CNRS, 1919 route de Monde, Montpellier, F-34293, France',
//   'Institut Européen des Membranes, UMR 5635, Campus CNRS, 1919 route de Mende, 34293 Montpellier Cédex 5, France',
//   'Institut Normand de Chimie Moléculaire Médicinale et Macromoléculaire',
//   'Normandie Univ UNIHAVRE FR 3038 CNRS URCOM 76600 Le Havre France',
//   'Normandie Univ UNILEHAVRE FR 3038 CNRS URCOM 76600 Le Havre France',
//   'Normandie Univ, France',
//   'Normandie Univ, France; UNILEHAVRE, FR 3038 CNRS, URCOM, EA 3221, 25 rue Philippe Lebon BP 1123, 76063 Le Havre cedex, France',
//   'Normandie Univ, UNIHAVRE, FR 3038 CNRS, URCOM, 76600, Le Havre, France',
//   'Normandie Univ, UNIHAVRE, URCOM EA 3221, FR CNRS 3038, 25, Rue Philippe Lebon CS 80540 Le Havre Cedex 76058 France',
//   'Normandie Univ, UNILEHAVRE, CNRS, URCOM, Le Havre cedex, France',
//   'Normandie Univ, UNILEHAVRE, FR 3032, CNRS, URCOM EA3221, Le Havre, France',
//   'Normandie Univ, UNILEHAVRE, FR3038 CNRS, URCOM, 76600 Le Havre, France',
//   'Normandie Univ., UNILEHAVRE, FR 3038 CNRS, URCOM, 76600 Le Havre, France',
//   'TU München, Lehrstuhl und Laboratorium für Wassergüte‐ und Abfallwirtschaft. Am Coulombwall, D‐85748 Garching',
//   'U.R.C.O.M., Université du Havre, 25 Rue Philippe Lebon, B.P. 540, F 76058 Le Havre Cedex, France',
//   'U.R.C.O.M., Université du Havre, 25, rue Philippe Lebon, BP 540, 76058 Le Havre cedex, France',
//   'UNIHAVRE FR 3038 CNRS URCOM Normandie Univ. Le Havre 76600 France',
//   'UNIHAVRE Normandie University  Le Havre France',
//   'UNIHAVRE, FR 3038 CNRS, URCOM, Normandie Univ., Le Havre 76600, France.',
//   'UNILEHAVRE, FR 3038 CNRS, URCOM Normandie Univ Le Havre France',
//   'UNILEHAVRE, FR 3038 CNRS, URCOM, EA 3221, 25 rue Philippe Lebon BP 1123, 76063 Le Havre cedex, France',
//   'UNILEHAVRE, FR 3038 CNRS, URCOM, EA 3221, Normandie University, France, 25 rue Philippe Lebon BP 1123, 76063 Le Havre cedex, France',
//   'UNILEHAVRE, FR 3038 CNRS, URCOM, EA 3221, Normandie University,76063 Le Havre, France',
//   'Unité de Recherche en Chimie Organique et Macromoléculaire',
//   'Unité de Recherche en Chimie Organique et Macromoléculaire, URCOM, EA 3221, Université du Havre, 25 Rue Philippe Lebon, B.P. 540, F- 76058 Le Havre cedex, France',
//   'Université du Havre, URCOM, EA 3221, FR CNRS 3038, 25 rue Philippe Lebon B.P. 540, 76058 Le Havre Cedex, France',
//   'Université du Havre, URCOM, EA 3221, FR CNRS 3038, 25 rue Philippe Lebon, B.P. 540, 76058 Le Havre cedex, France',
//   'Université du Havre, URCOM, EA 3221, FR CNRS 3038, 25, rue Philippe Lebon CS 80540, 76058 Le Havre Cedex, France.',
//   'Université Le Havre Normandie, Normandie Univ, URCOM, UR 3221, F-76600, Le Havre, France.',
//   'URCOM - Unité de Recherche en Chimie Organique et Macromoléculaire (25 rue Philippe Lebon\nBP 1123\n76063 Le Havre Cedex - France)',
//   'URCOM Université du Havre  EA 3221 FR CNRS 3038 25 rue Philippe Lebon B.P. 540 76058 Le Havre Cedex France',
//   'URCOM, EA 3221, FR CNRS 3038, University of Le Havre, 25 rue Philippe Lebon B.P. 540, 76058 Le Havre Cedex, France.',
//   'URCOM, Université du Havre, 25 rue Philippe Lebon, BP 540, 76058 Le Havre Cedex, France',
//   'URCOM, Université du Havre, 25 rue Philippe Lebon, BP 540, 76058 Le Havre cedex, France.',
//   'URCOM, UR 3221, Université Le Havre Normandie, Normandie Univ  Le Havre France',
// ];

const corpus = [
  'apple',
  'appl',
  'appel',
  'banana',
  'bananas',
  'banan',
  'orange',
  'oronge',
  'pear',
  'pair',
];

console.log('Corpus size:', corpus.length);
console.log(corpus);
